[package]
name = "app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tdx-attest-rs = { path = "../../QuoteGeneration/quote_wrapper/tdx-attest-rs"}
rand = "0.8.5"
