[package]
name = "tdx-attest-sys"
version = "0.1.0"
edition = "2018"
links = "tdx_attest"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.59.1"
