name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libboost-dev libboost-system-dev libboost-thread-dev
    - name: init submodule
      run: git submodule update --init --recursive
    - name: download prebuilt
      run: QuoteGeneration/download_prebuilt.sh
    - name: download SGXSDK
      run: |
        wget -r -l1 -np -nd --accept 'sgx_linux_x64_sdk_*.bin' https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu22.04-server/
        chmod +x ./sgx_linux_x64_sdk_*.bin
    - name: install SGXSDK
      run: ./sgx_linux_x64_sdk_*.bin <<< "yes"
    - name: build
      run: source ./sgxsdk/environment; make all
